name: Deploy Edge Function Otomatis

on:
  push:
    branches:
      - main # Ganti jadi 'master' jika branch utama Anda bernama master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari Repository
        uses: actions/checkout@v3

      - name: Pasang Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Kirim ke Supabase Cloud
        # Menggunakan --use-api agar proses deploy dilakukan langsung di server Supabase
        run: supabase functions deploy delete-user --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt --use-api
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
